---
title: "rstudio::conf 2019 notes"
author: "Tyler Bradley"
date: "1/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Thursday Keynote Address

## Joe Cheng - Shiny in production

  - production - sofware environments that are used and relied on by real users, with real consequences if things go wrong
  - prod environment - includes server, connect, and databases
  - best practives includes a staging system that is identical to your procudtion environment
  - production goals:
      * keep it up
      * keep it safe
      * keep it correct
      * keep it snappy
      
  - can shiny be used in production?
    * 2015 - yes it is possible
    * 2019 - yes it is easy
    
  - challenges for shiny in production
    * cultural challenges:
        - shiny apps are developed by R users who arent software engineers
        - dont know best practices for deployment to production
        
    * organizational challenges:
        - IT and management are skeptical
        - IT skew towards conservative
        - Skeptical of data scientists creating production artifacts
        - skeptical of technolofies they haven't heard of
        - Engineering department may not be on your side
    
    * Technical challenges
        - shiny makes developing apps easier but doesn't address automated testing, load testing, profiling, and deployment
        - R can be slow and is single threaded
        
  - New tools for shiny in production
    * RStudio Connect
    * shinytest (R package)
    * shinyloadtest (R package)
    * profvis - profiler for R
    * Plot caching - Dramatically speed up repeated plots
    * Async - last resort for dealing with slow operations
    
    
* Performance workflow
  1. Use shinyloadtest to see if its fast enough
  2. If not, use profvis to see whats making it slow
  3. Optimize
    i. Move work out of shiny (very often)
    ii. Make code faster (very often)
    iii. Use caching (sometimes)
    iv. use async (occasionally)
  4. Repeat!
  
* shinyloadtest - generates large amounts of realistic traffic to your app, then analyze latency
  1. Run of deploy your app
  2. Record an archetypal user session using shinyloadtest
  3. Playback the recording with your desired level of concurrency
  4. Analyze the data
  
  
* Doing work ahead of time
  - If preformance matters, avoid loading raw data in shiny, instead preprocess the data into a form shiny can read fast
  - feather is a much faster method for reading data than csv
  
  * Plot caching
       A app is a good candidate for plot caching if:
        1. the app has plot outputs that are time consuming to generate
        2. These plots are a significant fraction of the total amount of time the app spends thinking
        3. Most user are likely to request the same few plots 
      - use `renderCachedPlot` instead of `renderPlot` using the option `cacheKeyExpr`
      
      

## Session 1

### Push straight to prod - API Development with R and Tensorflow at T-mobile
**Heather Nolis and Jacqueline Nolis**

What does it mean to put something into production?
Analysis - Running code once to produce a result
Build - Writing code that is continuously running

Putting code into production is letting customers interact with data

Project: AL @ T-mobile

Goal: Use machine learning to improve the customer experience

Scenario: Customer sends messages
Goal: Prep customer care agent before first response: Current bill status
Method: Classigy the message with machine learning. 


MOdel building workflow:
  1. rmarkdown for explotatory analysis
  2. Save the model to flat files (and lof the build with rmarkdown)
  3. Show model off with a shiny demo
  
Choosing the language for prodution: **R**

Treat R like a full programming language:

  1. Commit is made to AI repo
  2. Jenkins builds the image
  3. Marathon orchestrates container deployment
  4. Mesos pushes to prodcution
  
Build the model into a plumber API!!

Behold: containers
  * Dockerfile - build instructions
  * Umage - the result of the docker file
  
Lessons Learned:
 * R & plumber close to parity with pyrhing and flask
 * R advantageous for quick data exploration
 * Language was never the project failpoint
 
### R in production 
**Mark Sellors**

*All of the technical barriers to running R in production are easy to overcome. It's the cultural barriers that slow us down.*

What is "production" anyway?
 -- "Production" is anything that is run repeatedly and that the business relies on

*R is great in production*

How do we get there?

Two paths to get R in production:

  1. Left hand path - the path of magic
  2. Right hand path - Getting the business to trust your work
  
*data science != software engineering*

*Production is a team sport*


### RStudio Connect: Past, Present, and Future
**Jeff Allen**

new in v1.7.0
  * programmable deployment
  * Content instrementations
  * Custumizable emails
  

### Configuration Management tools for the R Admin
**Kelly O'Bryant**

R Admin - A data scientists who has crawled into doing more IT-like work

R Admin Goals:
  1. Legitimacy - Get R recognized as an analytic standard
  2. Competencies - Understand and manage R tooling
  3. Adoption - Rely on integrated R base solutions
  
The value of a sandbox:
  1. Showcase the R toolchain
  2. Hands-on experience with analytic infrastructure
  3. Discover organization-specific solutions 
  
Ultimate Sandboxes - Reproduce custome analytic environments on demand with:
  **DevOps Flavor & Configuration Managament tools**
  1. Puppet
  2. Ansible
  **Ask your IT group what tool they use**
  
Ansible:
  * Server Management (SSH or an API)
  * Rich Module Ecosystem
  * Write playbooks in YAML
  `$ sudo pip install ansible`


### full_join - The role of data in reuniting families
**Brooke Watson**

Main role of data analysis in reunifications:
  1. Organize/Find
  2. Validate/Ask
  3. Describe/Understand
  
**The data souce is an important as the data itself**






  
